### ISSUE TITLE
Some of the older filters are not public classes

### ISSUE THREAD

**Issue by skfs** [bkiers/Liqp#107]
Some of the older filters are not public classes - this means that we cannot use them for testing, nor extend their functionality.
In our case, we have a String-like class (called "SafeString"), which sometimes is used and passed into the filters. We'd like to accommodate for this by extending some of the currently non-public filter classes by extracting the "non-safe" (and original String.class) value (mySafeString.getRaw() -> String.class) and pass it further down to a parent filter.

```java
public class OurSlizeFilter extends Slice {
	@Override
	public final Object apply(Object value, Object... params) {
		if(value instanceof SafeString){
			super.apply(((SafeString) value).getRaw(), params);
		} else {
			super.apply(value, params);
		}
	}
 [...]
```

But currently above is not possible.

Non-public classes are:

- `Append.java`
- `Capitalize.java`
- `Divided_By.java`
- `Downcase.java`
- `Escape.java`
- `Escape_Once.java`
- `First.java`
- `H.java`
- `Join.java`
- `Last.java`
- `Map.java`
- `Minus.java`
- `Modulo.java`
- `Newline_To_Br.java`
- `Plus.java`
- `Prepend.java`
- `Remove.java`
- `Remove_First.java`
- `Replace.java`
- `Replace_First.java`
- `Size.java`
- `Sort.java`
- `Split.java`
- `Strip_HTML.java`
- `Strip_Newlines.java`
- `Times.java`
- `Truncate.java`
- `Truncatewords.java`
- `Upcase.java`

**Comment by skfs** [comment]
Updated the code example, as there were some typos in there.

**Comment by skfs** [comment]
@bkiers, just out of curiosity; is there a particular reason for the listed classes not to be public?

**Comment by bkiers** [comment]
I can't remember :) I think I didn't envision built-in filters to be extended perhaps...
