### ISSUE TITLE
Arithmetic Operators (Numbers in String form)

### ISSUE THREAD

**Issue by sj5000** [bkiers/Liqp#110]
Should you check for "canBeInteger" here as well and other places where arithmetic operators are used? It doesn't seem to match the original liquid implementation of Shopify where integer - integer => integer

https://github.com/bkiers/Liqp/blob/master/src/main/java/liqp/filters/Minus.java#L21

**Comment by bkiers** [comment]
Hi, could you indicate how it exactly differs from the original?

**Comment by bkiers** [comment]
Wait, I read `isInteger(...)` but you said `canBeInteger(...)`. Hmm, yes, you may be right. I'll check.

**Comment by bkiers** [comment]
This ought to do it, I think: https://github.com/bkiers/Liqp/pull/111

**Comment by sj5000** [comment]
Thanks!

**Comment by sj5000** [comment]
thanks @bkiers for merging, mind releasing this in 0.7.7?

**Comment by sj5000** [comment]
Hi @bkiers, any idea when you plan to release this? I was kind of doing local hack on my end to getaround this problem, but if you are going to release this soon, I might as well use the released version. Thanks again for fixing this.

**Comment by bkiers** [comment]
@sj5000 https://github.com/bkiers/Liqp/issues/113

**Comment by bkiers** [comment]
0.7.7 is available: https://github.com/bkiers/Liqp/releases/tag/0.7.7

**Comment by sj5000** [comment]
thanks @bkiers
