### ISSUE TITLE
Should first and last array filters return the object in the arrays?

### ISSUE THREAD

**Issue by mbaumbach** [bkiers/Liqp#119]
While the examples are a bit light in the [docs](https://shopify.github.io/liquid/filters/first/), it seems like the `first` and `last` filters should simply return the first and last objects in the array and not try to coerce them into strings using `asString`. The following ways of accessing an array return different results:

```
# product = { title: 'Product title', price: 1299 }
# products is an array of product objects
{% assign prod = products | first %} # You get an asString representation here
{% assign prod = products.first %} # You get the full object here
```

I'm happy to submit a pull request if we agree this is the right change, but it should be as simple as removing the `super.asString` calls around the array accessors in both the `First` and `Last` filter classes.

**Comment by bkiers** [comment]
Hi @mbaumbach,

When I run the following in Ruby:

```ruby
require 'liquid'

product = { 'title' => 'Product title', 'price' => 1299 }
products = [product]

source = <<-HEREDOC
  {% assign first1 = products | first %}
  {% assign first2 = products.first %}

  product.price='{{product.price}}'
  first1.price='{{first1.price}}'
  first2.price='{{first2.price}}'
HEREDOC

@template = Liquid::Template.parse(source)

result = @template.render('product' => product, 'products' => products)

printf("%s", result)
```

the following is printed:

```
  product.price='1299'
  first1.price='1299'
  first2.price='1299'
```

So, yes, you are right: `| first` and `| last` should not _stringify_ what they return.

> I'm happy to submit a pull request [...]

Cool!
