### ISSUE TITLE
Proper Exception handling with line number reporting on error

### ISSUE THREAD

**Issue by subwiz** [bkiers/Liqp#12]
Is it possible to define a LiqpException class from which I can get details of template parsing errors?

**Comment by bkiers** [comment]
Yeah, error reporting and source locations where things went wrong are lacking. When I have some more spare time, I'll definitely have a look at this.

**Comment by fodon** [comment]
I second this. I parse a functioning liquid file and all I get in the error message is 
 java.lang.RuntimeException: MismatchedTokenException(57!=91)
Any clue how one would begin to debug this?

**Comment by bkiers** [comment]
The numbers refer to ANTLR's token types. MismatchedTokenException(57!=91) means that ANTLR encountered a token with type `57`, while the parser expected the token with type `91`. These token types are defined inside the generated `LiquidLexer`.

**Comment by jajcek** [comment]
Are there any plans to introduce this in the near future? Something like strict_variables and some info how to identify which one has failed (to be able to find this in the template)?

**Comment by bkiers** [comment]
Not in the near future. I do welcome PR's, of course :)

**Comment by blinksoft** [comment]
If there is someone interested in doing this as a paid engagement, please PM me.   We are trying to figure out if we want to do the work or outsource it, as this would help our support team identify issues easier.

**Comment by bkiers** [comment]
Here's a way you could go about providing better error messages: https://github.com/bkiers/Liqp/pull/56

For the time being, I'll leave that PR open for some feedback. Feel free to build upon that branch and submit a PR of your own.

HTH

**Comment by brettcooper** [comment]
Any progress or update on this issue?  We are also facing the issue of cryptic Liquid error messages that are difficult to understand or troubleshoot.  Better exception messaging would be greatly appreciated!

**Comment by bkiers** [comment]
@brettcooper ah yes, I already had some code on my local branch to handle runtime errors for filters which I forgot to push. I just did, and will be in then ext release. Thanks.

**Comment by brettcooper** [comment]
Woohoo @bkiers!  Thanks!  We look forward to trying the new exception handling.
