### ISSUE TITLE
Error in include cause include not rendering.

### ISSUE THREAD

**Issue by msangel** [bkiers/Liqp#124]
I will fix that by adding optional rendering flag that will cause exception instead of silently return empty line. 

See https://github.com/msangel/Liqp/pull/1 for current progress

Things included in merge request:

- `RenderSettings.showExceptionsFromInclude` field and its processing
- one another renderer (will create test cases where I will demonstrate why its needed)
- `Date` tag can be customizable  by providing custom type converter (I am using java8 Instant so this fix will made its compatible as well as with any other date type)
- Test case for INCLUDES_DIRECTORY_KEY feature. Found it quite useful. So decide to write test for it.

Or do I need to create separate merge requests for each improvement above?
The work still in progress.

**Comment by bkiers** [comment]
Great @msangel! Yes, I'd appreciate separate PR's if the changes are not related to each other. Separate PR's also make creating release notes much easier.

**Comment by msangel** [comment]
Created separate merge requests
