### ISSUE TITLE
Handling of maps in for-loops

### ISSUE THREAD

**Issue by hartfelt** [bkiers/Liqp#125]
Hello,

According to https://github.com/shopify/liquid/wiki/Liquid-for-Designers it should be possible to iterate a map with a forloop, like:

```
{% for item in hash %}
    {{ item[0] }}: {{ item[1] }}
{% endfor %}
```

I don't see any mention of this on https://shopify.github.io/liquid/tags/iteration/ though, but a quick test show that it is indeed supported by the ruby version:

```
$ cat test.rb 
require 'liquid'
@template = Liquid::Template.parse("{% for item in hash %}{{ item[0] }} is {{ item[1] }};{% endfor %}");
puts @template.render('hash' => {
	'a' => 'AAA',
	'b' => 'BBB'})
$ ruby test.rb 
a is AAA;b is BBB;
```

However, the current handling in liqp is to wrap the entire map in a list, resulting in one iteration where `item` is equals to `hash`. This behaviour is a result of `asArray(Object value) -> Object[]` in `LValue`, and is indeed documented in the comment there. Is this difference from the ruby version intentional or just an oversight?

As an experiment, in the codebase where I'm using liqp, I've copied the for-tag in order to add the following (quite hackish) case to asArray:

```
if (value instanceof Map) {
	return ((List<List<Object>>)((((Map)value).entrySet().stream().map(e -> Arrays.asList(
		((Map.Entry<Object, Object>)e).getKey(),
		((Map.Entry<Object, Object>)e).getValue())).collect(Collectors.toList())))).toArray();
}
```

...which makes the following test pass:

```
@Test
public void testLoopingMap() {
	Map<String, Object> inner = new HashMap<>();
	inner.put("a", "AAA");
	inner.put("b", "BBB");
	Map<String, Object> outer = new HashMap<>();
	outer.put("hash", inner);
	
	String o = Template.parse(
		"{% for item in hash %}" +
			"{{ item[0] }} is {{ item[1] }};" +
		"{% endfor %}").with(new HackedForTag()).render(outer);
	assertEquals("a is AAA;b is BBB;", o);
}
```

If the current behaviour is indeed an oversight, I'll work on cleaning up the above fix and submit it as a merge request, along with some tests.

Or, if some other approach is preferred, feel free to point me in the right direction ;)

-- 
Bjørn Hartfelt

**Comment by bkiers** [comment]
@hartfelt thanks for your detailed report. I will get back to you this weekend.

**Comment by hartfelt** [comment]
@bkiers Thanks for the quick reply. I'll look forward to your further comments :)

**Comment by msangel** [comment]
Actually this is the same problem as I tries to solve here https://github.com/bkiers/Liqp/issues/132

**Comment by msangel** [comment]
Working on my solution for cover this case too.

**Comment by bkiers** [comment]
Thanks, your solution was spot on. I only needed to unwrap the stream/collect calls since it (still) needs to be Java 7 compliant.

**Comment by hartfelt** [comment]
Great! Thanks for the quick resolution :+1:
