### ISSUE TITLE
Rendered bug

### ISSUE THREAD

**Issue by msangel** [bkiers/Liqp#132]
```java
    static class Foo {
        public String a = "A";
    }

    @Test
    public void renderMapWithPojosExistedThrowError() {
        Map<String, Object> data = new HashMap<String, Object>();
        data.put("foo", new Foo());
        String fooA = Template.parse("{{foo.a}}").render(data);

        assertThat(fooA, is("A"));
    }
```

**Comment by msangel** [comment]
Pick one:
https://github.com/bkiers/Liqp/pull/133
https://github.com/bkiers/Liqp/pull/134

**Comment by msangel** [comment]
The second is broken. Not evrything can be converted to map. Simplest failing case: String.

**Comment by msangel** [comment]
Well. Need more work on this.

**Comment by msangel** [comment]
My try \#<span>4 seems to be latest fix.

**Comment by bkiers** [comment]
Thanks @msangel for your contributions, much appreciated! I will have a look shortly.

**Comment by bkiers** [comment]
I had hoped to have a look at your PR's @msangel, but I didn't find the time yet. Kind of a hectic few weeks. Just a quick message that I didn't forget!

**Comment by msangel** [comment]
Done.

**Comment by bkiers** [comment]
Yes, fixed by `fix/132_3`

**Comment by bkiers** [comment]
Again, thanks @msangel. With all the merging, I did break something, I think. See https://github.com/bkiers/Liqp/issues/137. I'll have a closer look in a few days, but if you can easily spot what went wrong, feel free to send a PR 😉
