### ISSUE TITLE
`where` filter support

### ISSUE THREAD

**Issue by msangel** [bkiers/Liqp#138]
I have it already implemented here:
https://github.com/msangel/javyll/blob/master/src/main/java/ua/co/k/javyll/plugins/liquid/goodies/WhereFilter.java
But I will just port it to java7. 
And add some tests.

**Comment by msangel** [comment]
And will add support for null detection: 
https://jekyllrb.com/docs/liquid/filters/#detecting-nil-values-with-where-filter400

**Comment by bkiers** [comment]
Nice!
