### ISSUE TITLE
NoViableAlt thrown when assign tag has another tag name in it

### ISSUE THREAD

**Issue by nhoughto** [bkiers/Liqp#14]
When an assign tag tries to assign a value from an object, but the name of the objects property matches the name of another liquid tag, a NoViableAltException is thrown.

Easy to replicate with the following AssignTag test case

```
    @Test
    public void assignTestWithOtherTagName() throws Exception {

        assertThat(
                Template.parse("var2:{{var2}} {%assign var2 = var.comment%} var2:{{var2}}")
                        .render(" { \"var\": { \"comment\": \"content\" } } "),
                is("var2:  var2:content"));

        assertThat(
                Template.parse("var2:{{var2}} {%assign var2 = var.end%} var2:{{var2}}")
                        .render(" { \"var\": { \"end\": \"content\" } } "),
                is("var2:  var2:content"));
    }
```

Presumably some form of escaping needs to happen to not treat that value as a tag? Or maybe its something else entirely?

**Comment by bkiers** [comment]
Thanks for the report and the test! I will have a look at this.

**Comment by bkiers** [comment]
Fixed in https://github.com/bkiers/Liqp/commit/d0fe56679c01e89c634676326e31a371615a2ef7
