### ISSUE TITLE
Support for properties (dot notation)

### ISSUE THREAD

**Issue by benfortuna** [bkiers/Liqp#141]
Not sure if this should work or not. Given an object:

```
public class Resource {
  private String title;
  public Resource(String title) { this.title = title; }
  public String getTitle() { return title; }
```
Currently this will resolve to an object:

```
<html>
<head><title>{{resource}}</title></head>
<body>...</body>
</html>
```

But this will not (`liqp.exceptions.VariableNotExistException: Variable 'resource.title' does not exists`):

```
<html>
<head><title>{{resource.title}}</title></head>
<body>...</body>
</html>
```

**Comment by bkiers** [comment]
There is a way to do that. Have a look at https://github.com/bkiers/Liqp/blob/master/src/main/java/liqp/Template.java#L307 and the unit tests in https://github.com/bkiers/Liqp/blob/master/src/test/java/liqp/TemplateTest.java#L28

In your case, do this:

```java
String template = "{{resource.title}}";
String rendered = Template.parse(template).render(true, "resource", new Resource("MU"));
```

and `rendered` mill now be `"MU"`

**Comment by bkiers** [comment]
As a `Map` is also possible, btw:

```java
String template = "{{resource.title}}";
Map<String, Object> map = new HashMap<String, Object>(){{
    put("resource", new Resource("MU"));
}};
String rendered = Template.parse(template).render(map);
```

**Comment by benfortuna** [comment]
Ok, I am actually trying the Map version and it doesn't work for me. The complete example is actually using a javax.script.Bindings object as the Map, as I'm trying to make a simple liquid template engine:

https://github.com/micronode/whistlepost/blob/develop/extensions/whistlepost-scripting-liquid/src/main/java/org/whistlepost/scripting/liquid/LiquidScriptEngine.java#L29

Result of this input is the error mentioned above:

```
<html>
<head>
<title>{{resource.valueMap}}</title>
</head>
<body>
</body>
</html>
```

I'll test some more if I get time but meanwhile will focus on other template engines.

**Comment by bkiers** [comment]
If you could post code so that I could reproduce this in a unit test, I could have a look at it.
