### ISSUE TITLE
is there an example to use it in spring boot

### ISSUE THREAD

**Issue by ozkanpakdil** [bkiers/Liqp#144]
Hi

I checked but could not find any docs. is it possible to use liqp as template engine in spring boot ? or are there any doc how to do it ?

Thanks

**Comment by ozkanpakdil** [comment]
I wrote example to use viewresolver and liqp with it. but I am having problems about a public class. somehow its fields not coming in to the requested page. can you check https://github.com/ozkanpakdil/spring-examples/tree/master/gitpages the class Dana has title and spekerName but its not rendered.

Thanks

**Comment by bkiers** [comment]
Try making `title` and `speakerName` public instance variables.

**Comment by ozkanpakdil** [comment]
Thanks for the answer but it did not work. you can see it in the repo I shared before.

**Comment by bkiers** [comment]
Hmmm, when I checked your `Dana` file, I could have sworn I didn't see the `public` keyword...

**Comment by bkiers** [comment]
Anyway, I tried to run your spring boot app, but there are some methods that could not be resolved (automatic getters and setters that are probably generated by Lombok).

If you look in the `TemplateTest.renderObjectTest()` test, you will see that a POJO class gets rendered properly. Why it doesn't do so in your MVC app, I do not know.

**Comment by ozkanpakdil** [comment]
I know it looks like MVC is the reason for not rendering problem but I must point out.  in https://github.com/ozkanpakdil/spring-examples/blob/master/gitpages/src/main/java/com/mascix/starter/LiqpView.java lines below also generating empty titles and speaker names. which not directly related to MVC. I tried to giving template as string to also it did not change the result. I read the render functions but could not find the reason yet :(

`Template template = Template.parse(templateFile);
            String rendered = template.render(model);`

**Comment by bkiers** [comment]
> If you can create a unit test that reproduces it without the need of an entire MVC framework, feel free to reopen this issue and add the unit test to it. I will be more than happy to have a look at it.

☝️

**Comment by ozkanpakdil** [comment]
I have a class with main function has the same result here it is https://github.com/ozkanpakdil/liqptest

**Comment by bkiers** [comment]
When I run your `TestingLiqp` class, I get:

```
m:{presentations=[com.mascix.Dana@6121c9d6, com.mascix.Dana@87f383f, com.mascix.Dana@4eb7f003, com.mascix.Dana@eafc191, com.mascix.Dana@612fc6eb]}
-------------------:req dat:

  
    <div class="card mb-3 shadow-sm rounded">
              <div class="card-header">
                  <h5 class="card-title">title:tit0 - speaker:0</h5>
              </div>
              <div class="card-body">
                  
              </div>
          </div>
  
    <div class="card mb-3 shadow-sm rounded">
              <div class="card-header">
                  <h5 class="card-title">title:tit1 - speaker:1</h5>
              </div>
              <div class="card-body">
                  
              </div>
          </div>
  
    <div class="card mb-3 shadow-sm rounded">
              <div class="card-header">
                  <h5 class="card-title">title:tit2 - speaker:2</h5>
              </div>
              <div class="card-body">
                  
              </div>
          </div>
  
    <div class="card mb-3 shadow-sm rounded">
              <div class="card-header">
                  <h5 class="card-title">title:tit3 - speaker:3</h5>
              </div>
              <div class="card-body">
                  
              </div>
          </div>
  
    <div class="card mb-3 shadow-sm rounded">
              <div class="card-header">
                  <h5 class="card-title">title:tit4 - speaker:4</h5>
              </div>
              <div class="card-body">
                  
              </div>
          </div>
```

**Comment by ozkanpakdil** [comment]
hmm now we have a interesting case :) I have ```C:\Windows\system32>java -version
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)```

and I thought maybe intellij making something and ran the class from command line with mvn ```D:\Projects\liqp>mvn exec:java -Dexec.mainClass="com.mascix.TestingLiqp"
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------< com.mascix:liqptest >-------------------------
[INFO] Building my-app 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ liqptest ---
m:{presentations=[com.mascix.Dana@772b6584, com.mascix.Dana@4dbc50f7, com.mascix.Dana@e6c58b2, com.mascix.Dana@36be9f31, com.mascix.Dana@1a15cb27]}
-------------------:req dat:


    <div class="card mb-3 shadow-sm rounded">
              <div class="card-header">
                  <h5 class="card-title">title: - speaker:</h5>
              </div>
              <div class="card-body">

              </div>
          </div>

    <div class="card mb-3 shadow-sm rounded">
              <div class="card-header">
                  <h5 class="card-title">title: - speaker:</h5>
              </div>
              <div class="card-body">

              </div>
          </div>

    <div class="card mb-3 shadow-sm rounded">
              <div class="card-header">
                  <h5 class="card-title">title: - speaker:</h5>
              </div>
              <div class="card-body">

              </div>
          </div>

    <div class="card mb-3 shadow-sm rounded">
              <div class="card-header">
                  <h5 class="card-title">title: - speaker:</h5>
              </div>
              <div class="card-body">

              </div>
          </div>

    <div class="card mb-3 shadow-sm rounded">
              <div class="card-header">
                  <h5 class="card-title">title: - speaker:</h5>
              </div>
              <div class="card-body">

              </div>
          </div>

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.585 s
[INFO] Finished at: 2019-10-25T08:23:08+02:00
[INFO] ------------------------------------------------------------------------```

:) very interesting case to investigate. have a good day

**Comment by bkiers** [comment]
I copied your main class in my project with `0.7.9-SNAPSHOT`, but with `0.7.8` it indeed shows the same. It appears the `Dana` objects are not properly converted into `java.util.Map`s and therefor the keys `title` and `speakerName` could not be resolved. This was fixed in March: https://github.com/bkiers/Liqp/commit/2eb6bc8426c566db4c7f69297205e89324c2809a#diff-38af1b265e88e8390ac4e2a63aa61f32R348 and will be part of [the upcoming 0.7.9 release](https://github.com/bkiers/Liqp/issues/157). Thanks for reporting!

**Comment by ozkanpakdil** [comment]
Oh I am happy to hear that :) have a good weekend

**Comment by bkiers** [comment]
You too @ozkanpakdil!

**Comment by bkiers** [comment]
FYI Liqp version 0.7.9 is available in Maven Central. SO if you update your POM, it all should work.

https://github.com/bkiers/Liqp/releases/tag/0.7.9

**Comment by ozkanpakdil** [comment]
good news :) now I can finish my tests. I am trying to put liqp to https://github.com/jreijn/spring-comparing-template-engines let see the numbers :)

**Comment by bkiers** [comment]
Nice! 

I think Liqp is not going to be very fast though 🐢 😄

**Comment by ozkanpakdil** [comment]
Well I have good news. liqp is around jsp speed. which is the fastest in the list 😄 you can see the result here https://github.com/ozkanpakdil/spring-comparing-template-engines/blob/master/results.txt I must say I did not run these tests in a real server setup. just my laptop.

I also need to inform you I had some issues about rendering. there are some special objects was in the hashmap and it was disturbing liqp rendering. you can see those here https://github.com/ozkanpakdil/spring-comparing-template-engines/blob/06eb1edc6811e45008478a8e30067f6e81621117/src/main/java/com/jeroenreijn/examples/view/LiqpView.java#L25 

over all it is nice to play with these 😄 good day
