### ISSUE TITLE
DateTest fails if run with locale different than english

### ISSUE THREAD

**Issue by tunguski** [bkiers/Liqp#16]
```Date``` filter uses English locale always, but [DateTest lines 25-45](/bkiers/Liqp/blob/master/src/test/java/liqp/filters/DateTest.java#L25-L45) does not check what locale is set on computer running test.

It is only a bug in tests. Everywhere 

    new SimpleDateFormat(pattern)

is used

    new SimpleDateFormat(pattern, Locale.ENGLISH)

should be used.

**Comment by bkiers** [comment]
Thanks for reporting! Fixed in PR: https://github.com/bkiers/Liqp/pull/17
