### ISSUE TITLE
[Question] Extracting the list of variables from a template

### ISSUE THREAD

**Issue by maxArturo** [bkiers/Liqp#165]
I took a quick look at what's available from the public API, and it seems like it is not possible to get a list of variables for substitution from a template. What would be the easiest way to go about this? 

Thanks in advance!

**Comment by bkiers** [comment]
Sorry @maxArturo, I rarely visit this repo :) Will have a look at this shortly.

**Comment by bkiers** [comment]
No, there is no proper way to get hold of this data. A `Template` recently got a `TemplateContext` class that holds this information, but I don't see the need to make this publicly available. This hold more information than user-variables, but also internal variables used in for-loops. You could get a hold of it through reflection, of course, but that is rather fragile:

```java
Template template = Template.parse("{{Q}}");
template.render("Q", 42);

Field field = Template.class.getDeclaredField("templateContext");
field.setAccessible(true);

TemplateContext ctx = (TemplateContext) field.get(template);

System.out.println(ctx.get("Q"));
System.out.println(ctx.getVariables());
```

**Comment by andrhamm** [comment]
> I don't see the need to make this publicly available.

@bkiers This feature would be super useful in template tooling. I've searched for this feature in other LiquidJS libraries and have never found it, unfortunately. We write JSON Schemas for our templates in order to validate input at the API level and if we were able to parse out a list of the variables coded in the Liquid of a template, we could identify gaps where the schema might have become out of sync with the template, or even generate schemas programmatically. 😄 ✌️

**Comment by bkiers** [comment]
@andrhamm alright, fair enough, I'll re-open 😃

**Comment by andrhamm** [comment]
I'll be honest, I don't know much about the internals of a template engine, but ideally parsing a template could return an object with all the variables defined in the liquid. I would expect that object to match the structure of the input the template expects to receive.


```
<h1>People at {{company}}</h1>
<table>
    <thead>
        <td>Name</td>
        <td>Age</td>
        <td>Born On</td>
    </thead>
    <tbody>
    {% for person in people %}
        <tr>
            <td>{{ person.name | capitalize }}</td>
            <td>{{ person.age | round }}</td>
            <td>{{ person.born_at | date: "%a, %b %d, %y" }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
```

Could be parsed and return something resembling a schema of sorts:

```
[
  {
    "variable": {
      "key": "company",
      "type": "string",
      "occurrences": ["1:15-1:26"]
    }
  },
  {
    "variable": {
      "key": "people",
      "type": "array",
      "occurrences": ["3:1-9:13"],
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "occurrences": ["11:17-11:47"]
          },
          "age": {
            "type": "number",
            "occurrences": ["12:17-12:41"]
          },
          "born_at": {
            "type": "date",
            "occurrences": ["13:17-13:61"]
          }
        }
      }
    }
  }
]
```

I'm not sure how much context the parser would have about the scope of the variable, but ideally it could infer the data type if there are filters being used (math filters would imply a number type, default would be string). Of course nested loops could result in a very "deep" object. Arrays don't necessarily have to be uniform so if items don't conform the "items" property would have to reflect that.

**Comment by bkiers** [comment]
Ah, yeah, that makes sense. I was thinking about the values of the variables after rendering the template. Something what you described above is already possible with the abstract syntax tree that is available in the `Template`:

```java
Template template = Template.parse("...");
ParseTree root = template.getParseTree();
```

and then you can traverse the `root` tree (and its children) to get all variable nodes in it. I'll post a quick demo of it here this weekend.

**Comment by bkiers** [comment]
ANTLR provides [listener](https://github.com/antlr/antlr4/blob/master/doc/listeners.md) and visitor classes to walk the parse tree and extract information from it. You can get the parse tree from a template like this:

```java
String input = "<h1>People at {{company}}</h1>\n" +
        "<table>\n" +
        "    <thead>\n" +
        "        <td>Name</td>\n" +
        "        <td>Age</td>\n" +
        "        <td>Born On</td>\n" +
        "    </thead>\n" +
        "    <tbody>\n" +
        "    {% for person in people %}\n" +
        "        <tr>\n" +
        "            <td>{{ person.name | capitalize }}</td>\n" +
        "            <td>{{ person.age | round }}</td>\n" +
        "            <td>{{ person.born_at | date: \"%a, %b %d, %y\" }}</td>\n" +
        "        </tr>\n" +
        "    {% endfor %}\n" +
        "    </tbody>\n" +
        "</table>";

Template template = Template.parse(input);
ParseTree root = template.getParseTree();
```

You can then listen for invocations of certain rules, like the `lookup_id_indexes` parser rule:

```
lookup
 : id index* QMark?   #lookup_id_indexes
 | OBr Str CBr QMark? #lookup_Str
 | OBr Id CBr QMark?  #lookup_Id
 ;
```

that matches variables. You do that by extending the generated `LiquidParserBaseListener` class:

```java
class VariableListener extends LiquidParserBaseListener {

    @Override
    public void enterLookup_id_indexes(LiquidParser.Lookup_id_indexesContext ctx) {
        System.out.println(ctx.getText() + ", line: " + ctx.start.getLine() + ", index: " + ctx.start.getCharPositionInLine());
    }
}
```

Which can be used like this:

```java
VariableListener variableListener = new VariableListener();
ParseTreeWalker.DEFAULT.walk(variableListener, root);
```

Running the code will print the following:

```
company, line: 1, index: 16
people, line: 9, index: 21
person.name, line: 11, index: 19
person.age, line: 12, index: 19
person.born_at, line: 13, index: 19
```

Of course you could extend the `VariableListener` by recording in which scope variable live:

```
class VariableListener extends LiquidParserBaseListener {

    int scope = 0;

    @Override
    public void enterLookup_id_indexes(LiquidParser.Lookup_id_indexesContext ctx) {
        System.out.println("scope="+ scope + ": " + ctx.getText() + ", line: " + ctx.start.getLine() + ", index: " + ctx.start.getCharPositionInLine());
    }

    @Override
    public void enterBlock(LiquidParser.BlockContext ctx) {
        scope++;
    }

    @Override
    public void exitBlock(LiquidParser.BlockContext ctx) {
        scope--;
    }
}
```
