### ISSUE TITLE
Performance degradation of template parsing with custom tags

### ISSUE THREAD

**Issue by jonathanswenson** [bkiers/Liqp#170]
Problem: 

There appears to be a significant performance degradation when attempting to use custom tags and blocks in large templates. 

If you configure the parser to have two custom tags: `block` and `simple` (they will be no-ops for our purposes). 
However, we can assume that the simple tag does NOT use an end tag (like the built in increment tag) `endsimple` while the block tag (like the built in for tag) does `endblock` 

```
Tag.registerTag(new Tag("block") {    
    @Override public Object render(TemplateContext context, LNode... nodes) { return ""; }
});

Tag.registerTag(new Tag("simple_tag") {
    @Override public Object render(TemplateContext context, LNode... nodes) { return ""; }
});
```

Here is the most simple case, that exhibits the behavior (but as it is so small the perf degradation is not tangible)

```
{% block %}{% simple %}{% endblock %}
```

By increasing the number of characters between the `{% simple %}` tag and `{% endblock %}` we can see the performance start to degrade. 
This takes ~6 seconds to parse on my hardware (average of 10 runs after warming the JVM with an additional 10 runs)
```
{% block %}{% simple %}<100_000 characters>{% endblock %}
```

If the simple tag has an end to it takes around <20 ms to parse (18 for the first and 14 for the second -- again with average of 10 run after warming the JVM with 10 additional runs)
```
{% block %}{% simple %}<100_000 characters>{% endsimple %}{% endblock %}
or
{% block %}{% simple %}{% endsimple %}<100_000 characters>{% endblock %}
```

This further degrades if you add in additional block or simple tags: 
Takes ~16 seconds (again average of 10 after 10 warmup runs)
```
{% block %}
  {% simple %}
  {% block %} {% endblock %}
  {% block %} {% endblock %}
  {% block %} {% endblock %}
  <100_000 characters>
{% endblock %}
```

My Analysis: 

The first thing to notice is that the degradation seems to happen when falling back to the LL(\*) prediction mode after first failing with the SLL(\*) prediction mode. 
 
There are a few sources of ambiguity that may be related. 
+ Any end<xxx> can end any custom block (as long as it lexes as an `endId` token). 
  As such this parses without error: `{% block %}{% endwhatever %}` (this fails on ruby liquid with `Liquid::SyntaxError (Liquid syntax error: Unknown tag 'endwhatever')`)
  with Liqp this parses successfully (and renders as though you ended it with `endblock`)

  Additionally with two custom tags: `{% block1 %}{% block2 %}{% endblock1 %}{% endblock2 %}` the liqp parser determines that it is valid and seems to interprate it as swapping the order of the end blocks `{% block1 %}{% block2 %}{% endblock2 %}{% endblock1 %}`
  with Ruby liquid the template fails to parse: `Liquid::SyntaxError: Liquid syntax error: Unknown tag 'endblock1'`

+ There is no differentiation between blocks and tags -- in ruby you can override the Tag class or the Block class to get a custom tag or block. 
  Using and end<xxx> with a tag will cause a syntax error. 
  the template: `{% simple %} {% endsimple %}` fails with syntax error `Liquid::SyntaxError (Liquid syntax error: Unknown tag 'endsimple')` 
  with Liqp, this parses without error. 

+ In the case of using an un-ended tag within a block, the SLL mode appears to fail because it cannot tell which block is being ended. 
  To the parser it looks like this: `{% block %} {% simple %} {% endwhatever %}` and it is not clear whether the `endwhatever` tag applies to the block or the simple tag. 
  the SLL mode fails because as it is expecting a second `{% endsomething %}` tag `liqp.exceptions.LiquidException: parser error "extraneous input '<EOF>' expecting {OutStart, TagStart, Other, '{{', '{%'}" on line 1, index 42`
  The LL mode can handle this, but requires an aggressive lookahead strategy causing the perf degradation on larger inputs. 

I was able to fix the performance problem by making the lexer aware of the "blocks" and "tags", that were registered rather than allowing any identifier. It does not fall back to the LL parser mode, but potentially requires some breaking changes to the API in order to differentiate between blocks in tags.

**Comment by jonathanswenson** [comment]
cc @bkiers

**Comment by bkiers** [comment]
Hey @jonathanswenson, thank for the elaborate report! I hope to have a look at it more closely within a couple of days.
