### ISSUE TITLE
When I have properties that start with same characters there is a problem on rendering the template

### ISSUE THREAD

**Issue by mihaiandreicut** [bkiers/Liqp#172]
Hello,
I have this two properties
{{data.uniqueId}} and {{data.uniqueIdSolicitare}} used in the same div tag in a template, and I receive this error:

HTTP JVM: liqp.exceptions.LiquidException: lexer error "token recognition error at: '}"'" on line 98, index 0

Can you help me ?
thank you !

**Comment by msangel** [comment]
Hello @mihaiandreicut 
I have tested your case and found no problems with it.
Here's my test case:
```java
@Test
public void same_prefix_property() {
   String data = "{ \"data\" : {\"uniqueId\": \"ping\", \"uniqueIdSolicitare\":\"pong\"} }";
   assertThat(Template.parse("{{data.uniqueId}}-{{data.uniqueIdSolicitare}}").render(data),
           is("ping-pong"));
}
```

If I have missed something(flags, modes, data format), please give me to know.
