### ISSUE TITLE
Can I use ?

### ISSUE THREAD

**Issue by mihaiandreicut** [bkiers/Liqp#174]
Hello,
Can I use this kind of expression:
`
{% unless settings.fp_heading == blank %}
    <h1>{{ settings.fp_heading }}</h1>
{% endunless %}
`

Thank you !

**Comment by msangel** [comment]
You can(or at least should) use all the stuff the Jekyll/Liquid provide.
Your sample is not working in neither Jekyll or Liquid.
I just tested on both dialect this code:
```ruby
pp parse("{% unless settings.fp_heading == blank %} <h1>{{ settings.fp_heading }}</h1> {% endunless %}")
    .render!({"settings" => {"fp_heading" => ""}}, :strict_variables => true)
pp parse("{% unless settings.fp_heading == blank %} <h1>{{ settings.fp_heading }}</h1> {% endunless %}")
       .render!({"settings" => {"fp_heading" => nil}}, :strict_variables => true)
```
and in both Jekyll and Liquid I got this:
```bash
" <h1></h1> "
" <h1></h1> "
```

Yes, looks weird, but the library provide the same behavior as the Jekyll/Liquid.
