### ISSUE TITLE
About dynamic fields

### ISSUE THREAD

**Issue by MuratKaragozgil** [bkiers/Liqp#176]
Hi,

How to get dynamic fields in the input before render ?

Thanks

**Comment by msangel** [comment]
What do you mean by "dynamic fields"?

If you want to have computed values, take a look at liqp.parser.LiquidSupport class, sample usage in the test case below:
https://github.com/bkiers/Liqp/blob/master/src/test/java/liqp/parser/LiquidSupportTest.java#L44

**Comment by MuratKaragozgil** [comment]
For example

```
Template template = Template.parse("hi {{name}} {{surname}}");
Map<String, Object> map = new HashMap<String, Object>();
map.put("name", "tobi");
String rendered = template.render(map);
System.out.println(rendered);
```

{{name}} and  {{surname}} are dynamic field. How can i get name, surname etc. keywords from template object ?

Thanks

**Comment by msangel** [comment]
They are stored in the private field:
`template.templateContext.variables`
There is no getter for them(and depending on rendering mode library may convert them to a map), but in the general case, you can use reflection.

**Comment by msangel** [comment]
There no API for that. Sorry.
