### ISSUE TITLE
Grammars are in two locations

### ISSUE THREAD

**Issue by jvanzyl** [bkiers/Liqp#19]
I forked this project a long while back to add support for a Java implementation of Jekyll, and I'm trying to sync up my changes but you have the ANTRL grammars in duplicated in two places. Is IDEA using them in a different place than the Maven plugin? Just wanted to check before making pull requests as I have grammar changes and don't want to alter the wrong set.

**Comment by bkiers** [comment]
Hi Jason, yeah, I forgot to remove the grammar files in `src/grammar`. I just removed them in commit https://github.com/bkiers/Liqp/commit/5c20908eb911ed12e30799b4831ef2165daa181f

Thanks!
