### ISSUE TITLE
Make Include tag Jekyll friendly

### ISSUE THREAD

**Issue by jvanzyl** [bkiers/Liqp#20]
One of the additions I made in my fork was to create an IncludeJekyll tag that took the source directory of the includes from the context and didn't assume a default extension.

Would you mind a pull request that uses a source directory for the includes if one is provided in the context and uses the included resources name as-is if it has an extension? I will preserve the existing behaviour of using the `snippets` directory if a source directory is not provided and defaulting to the `.liquid` extension for included resources if one isn't provided.

**Comment by jvanzyl** [comment]
Just some context, I have a Java implementation of Jekyll that I've been using and I'd love to not to use my fork of your project :-)

**Comment by bkiers** [comment]
You're more than welcome to make a PR!

**Comment by jvanzyl** [comment]
Great, so any preference for the standard name for the key in the context for the source directory? Want me to make a constants class or want me to make a public static final in the Tags class?
