### ISSUE TITLE
Support Jekyll-like include tag

### ISSUE THREAD

**Issue by jvanzyl** [bkiers/Liqp#23]
Ultimately where I'm trying to get is to have the equivalent of:

https://jekyllrb.com/docs/templates/#includes

In my implementation of Jekyll using Liqp I only needed to support the Jekyll case and not the general case which is what Jekyll does overriding the standard include tag. I had to change your grammar slightly which allows me to use standard Jekyll in Ruby and my Java implementation which is super handy. But I'm not sure if this will break your standard use case. Jekyll allows things like:

{% include header.html %}

Where you don't need quotes around the included resource.

I'm happy to implement a way to selectively register tags with the default behaviour as it currently is. I can also make the include grammar bits more flexible. But I do need to change the grammar to support the Jekyll style. I can do whatever you prefer.

**Comment by bkiers** [comment]
Here's a quick demo of how this can be handled: https://github.com/bkiers/Liqp/tree/feature/configurable-flavors

**Comment by jvanzyl** [comment]
So will this allow me to override the existing `include` tag to make it Jekyll flavor?

**Comment by jvanzyl** [comment]
Cool, I see your tests and how to change the flavor.

**Comment by bkiers** [comment]
Cool. I've created a PR for this: https://github.com/bkiers/Liqp/pull/25

Any objections/recommendation for your use case?
