### ISSUE TITLE
Plus filter is wrong

### ISSUE THREAD

**Issue by RobertoPegoraro** [bkiers/Liqp#233]
According the Liquid code, there is a strategy before calculate the Plus

It checks and convert in case not a number

def self.to_number(obj)
      case obj
      when Float
        BigDecimal(obj.to_s)
      when Numeric
        obj
      when String
        /\A-?\d+\.\d+\z/.match?(obj.strip) ? BigDecimal(obj) : obj.to_i
      else
        if obj.respond_to?(:to_number)
          obj.to_number
        else
          0
        end
      end
    end

But the Liqp is just checking if it's a number, I need it like the official code, because I need to use the Plus for date like "2022-03-24"

**Comment by msangel** [comment]
@RobertoPegoraro can you please provide sample test case that is failing and I will roll up fix fit it?

This will boost fix much as I don’t know ruby good enough(so figuring out error will take much more time)

**Comment by msangel** [comment]
Or at least more details. As for now I see you need to add string that look like a date "2022-03-24" to something. What exact java type is the date object? What is the second operand?

**Comment by RobertoPegoraro** [comment]
In my case is it. I'll pass the date as String:

`"{% assign ptDate = '2022-03-24' | date: '%s' %} {{ ptDate | plus: 518400 | date: \"%B %-d, %Y\"}}"`

**Comment by RobertoPegoraro** [comment]
I figure out the problem is not in Plus, but in my code there is a time_zone function (is not native from liquid) so, I created a new filter and now the plus is working as expected. thank you!
