### ISSUE TITLE
Parsing Datetime to date-month works fine but not with only Date

### ISSUE THREAD

**Issue by jkhanna23** [bkiers/Liqp#240]
Hi, I'm having an issue while parsing the following input in Template to render.

{{ "2022-10-13 12:06:04" | date: "%m-%e" }}     → gives parsing outcome as →      "10-13"                   // correct output

{{ "2022-10-13" | date: "%m-%e" }}                     → gives parsing outcome as →      "2022-10-13"        //incorrect output

Is there any method or filter for this issue so it works with only date input as well?
@bkiers @msangel

**Comment by bkiers** [comment]
Thanks for the report @jkhanna23, I've created a fix for it. I'll leave the merge to @msangel since I am not using Liqp actively myself.

**Comment by jkhanna23** [comment]
Hi @bkiers @msangel,

Can you please make a new tag/version for the repo with these changes made above, as I'm currently using the tag - **0.7.5** for liqp

**Comment by bdale-upland** [comment]
I have the same question as jkhanna23 above - any ETA on the next release with this fix in it?
Thanks!
