### ISSUE TITLE
Upgrade ANTLR

### ISSUE THREAD

**Issue by mbaumbach** [bkiers/Liqp#256]
Hello! As I was upgrading some projects that use Liqp, I found a dependency conflict that seems to require an upgrade to ANTLR. In my project, I'm using Hibernate 6.1 and that has an ANTLR dependency of 4.10.1. When trying to use Liqp in that project, I get the following error from ANTLR when trying to parse templates:

```
Could not deserialize ATN with version 3 (expected 4)
```

Testing with a local copy of Liqp upgraded to 4.10.1 seems to fix the issue. I'm proposing we upgrade the dependency in Liqp as well unless there's a better way to manage those differences. I'll open a PR with the change as well.

**Comment by mbaumbach** [comment]
Thanks @msangel! Any plans to build a new release soon?

**Comment by msangel** [comment]
Yes, I probably will do one these days with what we have in master. There is one [open discussion](https://github.com/bkiers/Liqp/issues/254) about what the library should look like in the future but for now, the code is fully compatible and nothing stops to release the intermediate version.

**Comment by mbaumbach** [comment]
Thanks @msangel! It doesn't look like there's any planned features for this intermediate version that I can see in the issues/open discussion, but if there is anything I can help with to help get a new release out, let me know and I'd be happy to. Thanks again!

**Comment by msangel** [comment]
@mbaumbach needs more discussion on this as the library upgrade caused requirements of JDK upgrade too from 1.8 to 11, and still a lot of usage of java 8 in place.

**Comment by msangel** [comment]
https://github.com/bkiers/Liqp/issues/256

**Comment by msangel** [comment]
I simply cannot build this locally as I have only java 1.8 on my working machine...

**Comment by msangel** [comment]
as an option, have different builds/version for java 8 and java 11

**Comment by mbaumbach** [comment]
That could work. Another option is to do a major version bump for the Java 11 builds and then another later on for the deprecations discussed in #254.

I'm happy to help with any of the builds/releases if that's helpful. Just let me know!

**Comment by mbaumbach** [comment]
Another option to help with this could be to use GitHub actions that trigger off a release/tag being created and that publishes to Maven Central/Sonatype. Any secrets needed for publishing could be stored in the GitHub project's secrets/variables section and just referenced with the corresponding environment variable. This is [one example](https://bjansen.github.io/java/2021/02/03/deploying-to-maven-central-using-github-actions.html).

We'd still need to figure out how to version/tag things if doing separate java 8 and 11 releases, but I would presume that's best done with a major version bump for 11.

**Comment by KDMK** [comment]
Hello. We have exactly the same conflict with this library and Hibernate 6 so I am interested in when could we expect this to be released?

Don't hesitate to reach me if you see that I could assist you in any way.

**Comment by kohlschuetter** [comment]
We could also relocate all antlr-dependent code using maven-shade-plugin so there are no further conflicts with other code. That way, we can keep Java 8 compatibility.

To do this, we may have to remove `Template#getParseTree` from the public API.

**Comment by msangel** [comment]
@kohlschuetter the one that will move `org.antlr` package into `liqp.org.antlr` ? 
Well, sounds like a plan and the only viable solution here to make everyone happy while keeping a single version and java 8 and 11 compatibility. 
Regarding `Template#getParseTree` - hard question.  Java 8 is still in wild use....
