### ISSUE TITLE
Shaded jar should exclude non-ANTLR dependencies

### ISSUE THREAD

**Issue by scott-seguno** [bkiers/Liqp#272]
The shaded JAR being built currently includes all of the dependencies. The fix is to allow only ANTLR and let the other dependencies be brought in transitively through the POM. I have created a PR for this: https://github.com/bkiers/Liqp/pull/271

**Comment by msangel** [comment]
Verified, merged, and version enrolled.
Thanks!
![Screenshot_2023-05-21_02-28-54](https://github.com/bkiers/Liqp/assets/773163/90e1c53d-2206-4be9-811c-3f327ed1b98c)

**Comment by scott-seguno** [comment]
Thanks very much!
