### ISSUE TITLE
Template parse is deprecated

### ISSUE THREAD

**Issue by shlomielbaz** [bkiers/Liqp#283]
Hello all,

the framework says: 'parse(java.lang.String)' is **deprecated**

I am trying to use the **liqp** as the following

```
final Template template = Template
                .parse(HTML)
                .withRenderSettings(renderSettings);
```

What am I missing?

**Comment by msangel** [comment]
@shlomielbaz hello!
Yes, the API has been changed, but that so far is not reflected in the documentation.
Your sample with the latest published library version will be:
```java
final TemplateParser parser = new TemplateParser.Builder()
                                           .withRenderSettings(renderSettings)
                                           .build();
final Template template = parser.parse(HTML);
```

The working code in the `master` brunch also has changed in that. RenderSettings object is removed and all its properties are moved into the TemplateParser object directly.

**Comment by msangel** [comment]
(since no one clearly knows why one settings are declared as `rendering`, another as `parse` and some as `protected`)

**Comment by shlomielbaz** [comment]
thank you for your quick response, I will try it,
Thanks again
