### ISSUE TITLE
Issues with the new release.

### ISSUE THREAD

**Issue by aakash10897** [bkiers/Liqp#285]
I am using this library and I see that there are quite a lot of changes that are in "master" branch but are not yet released. 
For example the use of ParseSettings is not there in master branch anymore but is being used in 0.8.5.3. 
In 0.8.5.3 release there are a lot of bugs.
For example the default flavour for ParseSettings is LIQUID but the filters and insertions are not getting initialised for ParseSettings, so I had to do it like this 
   ```
    Flavor.LIQUID.getFilters().values().forEach(parseSettingsBuilder::with);
        Flavor.LIQUID.getInsertions().values().forEach(parseSettingsBuilder::with);
        return parseSettingsBuilder.build();
```
The README is also not updated. It still refers to 0.8.3.3 which doesn't have TemplateParser. I am using this professioally.

**Comment by msangel** [comment]
Hello!
Yep, we are aware the problem.
Work is in progress.
Next release will contain readme update as well. 

Keeping this ticket opened as this is known issue.

**Comment by aakash10897** [comment]
I was going to raise PR for the ParseSettings one but saw that we are trying to get rid of it.
But really appreciate the efforts as this is the only solution for liquid template engine for Java.
