### ISSUE TITLE
!= working as ==

### ISSUE THREAD

**Issue by aakash10897** [bkiers/Liqp#286]
[`{%-](<img width="1046" alt="Screenshot 2023-10-06 at 7 43 54 PM" src="https://github.com/bkiers/Liqp/assets/25743992/84c60a19-0d0d-444b-9270-634161fc6dab">) assign value = 5.0 | round: 1 -%} {%- if value >= 4.0 and value <= 4.2 -%} Très bien {%- elsif value >= 4.3 and value <= 4.7 -%} Superbe {%- elsif value >= 4.8 and value <= 4.9 -%} Fabuleux {%- elsif value != 5.0 -%} Exceptionnel {% endif %}`

the above template is rendering to "Exceptionnel" where as it should return empty.

`{%- assign value = 5.0 | round: 1 -%} {%- if value >= 4.0 and value <= 4.2 -%} Très bien {%- elsif value >= 4.3 and value <= 4.7 -%} Superbe {%- elsif value >= 4.8 and value <= 4.9 -%} Fabuleux {%- elsif value == 5.0 -%} Exceptionnel {% endif %}`

This one is rendering to "" whereas it should render to "Exceptionnel"

Correct rendering from shopify.dev
<img width="1042" alt="Screenshot 2023-10-06 at 7 44 02 PM" src="https://github.com/bkiers/Liqp/assets/25743992/6dcbc1ec-13e1-4363-b472-ff2491e9cf8b">

<img width="1046" alt="Screenshot 2023-10-06 at 7 43 54 PM" src="https://github.com/bkiers/Liqp/assets/25743992/9f558380-088e-49e5-9088-b86698dcabc4">

**Comment by msangel** [comment]
Hello!
I am working on related bug right now. Will add this test case for checking too.

**Comment by msangel** [comment]
done in master, (now need to prepare release)
