### ISSUE TITLE
Protection against malicious users

### ISSUE THREAD

**Issue by kutchar** [bkiers/Liqp#29]
I'm planning of using Liqp for a user-facing app where users can create templates and I've been thinking about security and I couldn't really see how the following cases are handled in the codebase:
1. Limiting of the maximum number of iterations per render run (i.e. don't allow a malicious user to loop infinitely or create very long loops)
2. Having a circuit breaker for how large of a template output can be rendered. (i.e. don't create a massive string)
3. Having a timeout on how long should template generation take

Also, are there any other scenarios that I left out?

**Comment by bkiers** [comment]
> [...] I couldn't really see how the following cases are handled in the codebase

That is correct, there are no guards in place.

> Also, are there any other scenarios that I left out?

Not that I can think of.

**Comment by bkiers** [comment]
FYI, working on this feature: https://github.com/bkiers/Liqp/tree/feature/29-template-protection

**Comment by bkiers** [comment]
Also added a fourth point: the maximum amount of characters a template can be (before rendering/parsing)

**Comment by bkiers** [comment]
Alright, this functionality is now in `master` and I've updated the `README`. Thanks for your suggestions!

**Comment by kutchar** [comment]
@bkiers This is great, thanks
