### ISSUE TITLE
[Question]Is it possible to implement a Django-like block inheritance?

### ISSUE THREAD

**Issue by lordscales91** [bkiers/Liqp#30]
I've seen this gem for the official Liquid engine in Ruby https://github.com/danwrong/liquid-inheritance which provides [such functionality](https://docs.djangoproject.com/en/dev/ref/templates/language/#template-inheritance). I would like to implement it in this library. Is that possible?

I think it is possible but I'm not sure. To implement this we need 2 new tags: `extends` and `block`. The block tag will be just a custom block to mark inheritable blocks and provide the ability to call the parent block (we also would need to support the `{{ block.super }}` syntax somehow. Maybe by injecting a special variable in the context). With the extends tag we need to parse the parent template, render any content outside of an inheritable block, and inject the inheritable blocks in the current template.

I think that just using `Tag.registerTag()` with the mentioned new tags will not be enough. Probably we would need to change something else in the codebase.

**Comment by bkiers** [comment]
I know, rather late :)

But just in case anyone else stumbles upon this and wants this too.

> [...] Probably we would need to change something else in the codebase.

I've read through the links provided, and I'm not going to support this in Liqp unfortunately.
