### ISSUE TITLE
BlockNode Map render issue: String.valueOf(Map<?,?>) returns '=' instead of ':' as delimiter

### ISSUE THREAD

**Issue by fw-udbhav** [bkiers/Liqp#303]
Tag 0.8.3.3 uses "String.valueOf(value)" in BlockNode even if the value is a Map or a complex object.

which results in rendering the map to non pretty output which includes '=' instead of ':' as the delimiter.

I have added a fix for this using Java libraries only here:
https://github.com/bkiers/Liqp/pull/302

**Comment by msangel** [comment]
Hello!

I will check this code against ruby behavior some these days and if it follows it, I will merge it.

**Comment by fw-udbhav** [comment]
okay. thanks @msangel 
will wait for the same.

**Comment by msangel** [comment]
@fw-udbhav could you please explain why previous way of rendering map is issue and the ":" should be used instead of "="? 
I tried Ruby and it uses "=>" notation for hashes(Ruby's equivalent for maps) as only option:
![image](https://github.com/bkiers/Liqp/assets/773163/6c2f12d1-96ec-41b1-a904-cded32219853)

**Comment by msangel** [comment]
From the PR:
> String.valueOf(mapObject) will give '=' instead of ':' as the delimiter which:
> - doesn't look pretty as we say in pretty print.
> - it's not easy to decode while reading.

1.
> doesn't look pretty as we say in pretty print 

No one said it should be "pretty". it simply uses default Object#toString which is expected output in this case.

2.
> it's not easy to decode while reading.

Its opinion-based. I have equal decoding skills for both "=" and ":"

**Comment by msangel** [comment]
As for me these reasoning is simply not enough

**Comment by msangel** [comment]
If you want map to be converted to JSON object, simply create a filter for that and use it. Map is a map.

**Comment by pmenhart** [comment]
> If you want map to be converted to JSON object, simply create a filter for that

@msangel Perhaps the library should provide a standard filter `json` that converts its parameter into a JSON format? See https://shopify.dev/docs/api/liquid/filters/json

**Comment by fw-udbhav** [comment]
@msangel 
I agree. Keeping the delimiter to "=" doesn't break anything but as json follows the ":" practice, it just looks cleaner even though it's subjective. 

and as @pmenhart mentioned, json filter can also be a good option but not sure if it's available with liqp or not.
I see liqp do have the following doc in the liqp.filters.Filter class:

/**
 * Output markup takes filters. Filters are simple methods. The first
 * parameter is always the output of the left side of the filter. The
 * return value of the filter will be the new left value when the next
 * filter is run. When there are no more filters, the template will
 * receive the resulting string.
 * <p/>
 * -- https://github.com/Shopify/liquid/wiki/Liquid-for-Designers
 */

which does use a set of filters. Does it support json or anything similar currently ? - otherwise I will create a custom filter.

**Comment by msangel** [comment]
Yes. The ‘json’ filter should be added

**Comment by msangel** [comment]
`json ` filter added to versions `0.9.0.2` (and `0.8.3.4` as `0.8.3.3` was pointed as starting point)
maven repo sync might take some time

**Comment by fw-udbhav** [comment]
@msangel - that's great. I will test it out. thanks.
