### ISSUE TITLE
Releases to Maven Central

### ISSUE THREAD

**Issue by jvanzyl** [bkiers/Liqp#33]
I'm happy to coordinate and do releases to Maven Central if you don't have time. I'm about to do a first release of my Jekyll-clone and I'd like to get Liqp into Maven Central so Idiom will build. Thanks.

**Comment by bkiers** [comment]
> I'm happy to coordinate and do releases to Maven Central if you don't have time.

Yes, that'd be great!

**Comment by jvanzyl** [comment]
Ok, everything is ready. I will cut a release when you'd like me to. I can do it in my fork and PR back the changes or I can do it directly on this repo with access. Whatever you prefer.

**Comment by bkiers** [comment]
Feel free to do it directly on this repo. I added you as a collaborator (with push access).

Again, thanks!

**Comment by jvanzyl** [comment]
First release is here, let me know if you want the branches merge differently. I released on master and then merged to develop.

http://repo1.maven.org/maven2/nl/big-o/liqp/0.6.6/
