### ISSUE TITLE
Template.parse performance when lots of custom tags are in the content

### ISSUE THREAD

**Issue by realiteer** [bkiers/Liqp#37]
We implemented a custom tag "snippet" to allow users to define reusable chunks of HTML. Works like a charm... Until there are > 20 tags present in the same content. Then it starts to drastically slow down the more tags are present.

Wrote the following unit test to demonstrate:

    @Test
    public void testCustomTags() {
        final StopWatch stopWatch = new StopWatch();

        for (int n=0; n<30; n++) {
            final String content = StringUtils.repeat("{% snippet \"face\" %}", n);

            stopWatch.start();
            Template.parse(content);
            stopWatch.stop();
            LOG.debug("{} tags -> {} milliseconds", n, stopWatch.getTime());
            stopWatch.reset();
        }
    }

Here is some sample output when using custom tags:

1 tags -> 0 milliseconds
2 tags -> 0 milliseconds
3 tags -> 0 milliseconds
4 tags -> 0 milliseconds
5 tags -> 1 milliseconds
6 tags -> 6 milliseconds
7 tags -> 1 milliseconds
8 tags -> 2 milliseconds
9 tags -> 4 milliseconds
10 tags -> 6 milliseconds
11 tags -> 9 milliseconds
12 tags -> 11 milliseconds
13 tags -> 11 milliseconds
14 tags -> 17 milliseconds
15 tags -> 33 milliseconds
16 tags -> 61 milliseconds
17 tags -> 79 milliseconds
18 tags -> 134 milliseconds
19 tags -> 230 milliseconds
20 tags -> 464 milliseconds
21 tags -> 887 milliseconds
22 tags -> 1727 milliseconds
23 tags -> 3393 milliseconds
24 tags -> 6865 milliseconds
25 tags -> 13781 milliseconds
26 tags -> 28804 milliseconds
27 tags -> 56767 milliseconds

Fortunately, standard tags do not have the same problem. Wrote the following unit test to demonstrate:

    @Test
    public void testStandardTags() {
        final StopWatch stopWatch = new StopWatch();

        for (int n=0; n<30; n++) {
            final String content = StringUtils.repeat("{% if data.face == \"happy\" %}{% endif %}", n);

            stopWatch.start();
            Template.parse(content);
            stopWatch.stop();
            LOG.debug("{} tags -> {} milliseconds", n * 2, stopWatch.getTime());
            stopWatch.reset();
        }
    }

And here is some sample output when using standard tags:

2 tags -> 1 milliseconds
4 tags -> 0 milliseconds
6 tags -> 0 milliseconds
8 tags -> 6 milliseconds
10 tags -> 1 milliseconds
12 tags -> 1 milliseconds
14 tags -> 1 milliseconds
16 tags -> 1 milliseconds
18 tags -> 1 milliseconds
20 tags -> 1 milliseconds
22 tags -> 1 milliseconds
24 tags -> 1 milliseconds
26 tags -> 1 milliseconds
28 tags -> 2 milliseconds
30 tags -> 2 milliseconds
32 tags -> 1 milliseconds
34 tags -> 1 milliseconds
36 tags -> 1 milliseconds
38 tags -> 1 milliseconds
40 tags -> 1 milliseconds
42 tags -> 1 milliseconds
44 tags -> 1 milliseconds
46 tags -> 1 milliseconds
48 tags -> 1 milliseconds
50 tags -> 1 milliseconds
52 tags -> 1 milliseconds
54 tags -> 1 milliseconds

**Comment by bkiers** [comment]
Thanks for the detailed report @realiteer! I'll have a closer look.

**Comment by bkiers** [comment]
I'm in the porting the ANTLR3 grammar to the newer v4 version, and this is now what I get with the newer v4 version of ANTLR:

```java
import liqp.nodes.LNode;
import liqp.tags.Tag;
import org.codehaus.plexus.util.StringUtils;
import org.junit.Test;
import com.google.common.base.Stopwatch;

public class Demo {

    @Test
    public void testCustomTags() {

        Tag.registerTag(new Tag("snippet") {
            @Override
            public Object render(TemplateContext context, LNode... nodes) {
                return "NADA";
            }
        });

        final Stopwatch stopwatch = new Stopwatch();

        for (int n = 1; n < 60; n++) {
            final String content = StringUtils.repeat("{% snippet \"face\" %}", n);

            stopwatch.start();
            Template.parse(content);
            stopwatch.stop();
            System.out.printf("script size=%s, tags=%s -> %s milliseconds\n", content.length(), n, stopwatch.elapsedMillis());
            stopwatch.reset();
        }
    }
}
```

output:

```
script size=20, tags=1 -> 278 milliseconds
script size=40, tags=2 -> 8 milliseconds
script size=60, tags=3 -> 3 milliseconds
script size=80, tags=4 -> 3 milliseconds
script size=100, tags=5 -> 4 milliseconds
script size=120, tags=6 -> 4 milliseconds
script size=140, tags=7 -> 5 milliseconds
script size=160, tags=8 -> 5 milliseconds
script size=180, tags=9 -> 5 milliseconds
script size=200, tags=10 -> 4 milliseconds
script size=220, tags=11 -> 3 milliseconds
script size=240, tags=12 -> 5 milliseconds
script size=260, tags=13 -> 4 milliseconds
script size=280, tags=14 -> 4 milliseconds
script size=300, tags=15 -> 9 milliseconds
script size=320, tags=16 -> 5 milliseconds
script size=340, tags=17 -> 6 milliseconds
script size=360, tags=18 -> 6 milliseconds
script size=380, tags=19 -> 6 milliseconds
script size=400, tags=20 -> 6 milliseconds
script size=420, tags=21 -> 9 milliseconds
script size=440, tags=22 -> 15 milliseconds
script size=460, tags=23 -> 12 milliseconds
script size=480, tags=24 -> 12 milliseconds
script size=500, tags=25 -> 9 milliseconds
script size=520, tags=26 -> 14 milliseconds
script size=540, tags=27 -> 10 milliseconds
script size=560, tags=28 -> 7 milliseconds
script size=580, tags=29 -> 10 milliseconds
script size=600, tags=30 -> 27 milliseconds
script size=620, tags=31 -> 17 milliseconds
script size=640, tags=32 -> 8 milliseconds
script size=660, tags=33 -> 16 milliseconds
script size=680, tags=34 -> 9 milliseconds
script size=700, tags=35 -> 18 milliseconds
script size=720, tags=36 -> 13 milliseconds
script size=740, tags=37 -> 13 milliseconds
script size=760, tags=38 -> 14 milliseconds
script size=780, tags=39 -> 15 milliseconds
script size=800, tags=40 -> 23 milliseconds
script size=820, tags=41 -> 19 milliseconds
script size=840, tags=42 -> 19 milliseconds
script size=860, tags=43 -> 25 milliseconds
script size=880, tags=44 -> 20 milliseconds
script size=900, tags=45 -> 27 milliseconds
script size=920, tags=46 -> 20 milliseconds
script size=940, tags=47 -> 20 milliseconds
script size=960, tags=48 -> 19 milliseconds
script size=980, tags=49 -> 24 milliseconds
script size=1000, tags=50 -> 26 milliseconds
script size=1020, tags=51 -> 25 milliseconds
script size=1040, tags=52 -> 20 milliseconds
script size=1060, tags=53 -> 22 milliseconds
script size=1080, tags=54 -> 20 milliseconds
script size=1100, tags=55 -> 19 milliseconds
script size=1120, tags=56 -> 17 milliseconds
script size=1140, tags=57 -> 12 milliseconds
script size=1160, tags=58 -> 16 milliseconds
script size=1180, tags=59 -> 13 milliseconds
```
