### ISSUE TITLE
Support 'Whitespace Control'

### ISSUE THREAD

**Issue by cjbrooks12** [bkiers/Liqp#39]
See [the official Liquid documentation](https://shopify.github.io/liquid/basics/whitespace/). Whitespace around rendered blocks should be able to be removed by adding a dash to each tag. Would also be nice to support a global option to never render that whitespace.

**Comment by mosabua** [comment]
That would be great for tighter HTML generation but especially also for creation of JSON files and other resources that need to be processes by some downstream tools. I had to collapse all my liquid commands into a line and it makes it hard to maintain (and read).

**Comment by bkiers** [comment]
Alright, added support for these two enhancements: https://github.com/bkiers/Liqp/pull/44

**Comment by mosabua** [comment]
Sweet ... now we are all hoping for a new release soon @bkiers

**Comment by bkiers** [comment]
> Sweet ... now we are all hoping for a new release soon @bkiers

@jvanzyl would you be so kind as to push a new release (0.6.8) to Maven Central?
