### ISSUE TITLE
Static methods: can it be made instance based?

### ISSUE THREAD

**Issue by subwiz** [bkiers/Liqp#4]
`Filter.registerFilter()` and `Tag.registerTag()` are static methods. Not able to plug different implementations during runtime as any change affects globally across the JVM.

**Comment by bkiers** [comment]
That sounds like a reasonable feature. The `static` methods will still be there to add filters over all instances.

https://github.com/bkiers/Liqp/pull/8

**Comment by subwiz** [comment]
Thanks :-)
