### ISSUE TITLE
Breadcrumb related parsing problems

### ISSUE THREAD

**Issue by mosabua** [bkiers/Liqp#43]
I have a include file in Jekyll that add breadcrumbs which looks like this

```
{% assign crumbs = page.url | split: '/' %}
<div style="font-size: 12px;">
  <p><a href="/">Home</a> >
  {% for crumb in crumbs offset: 1 %}
    {% if forloop.last %}
      <span style="font-weight: bold;">{{ page.title }}</span>
    {% else %}
      <a href="{% assign crumb_limit = forloop.index | plus: 1 %}{% for crumb in crumbs limit: crumb_limit %}{{ crumb | append: '/' }}{% endfor %}"
        style="text-transform: capitalize"
      >{{ crumb | replace:'-',' '}}</a> > 
    {% endif %}
  {% endfor %}</p>
</div>
```

This works fine with Jekyll 3.3.1. When using my liqp based parsing in a java jekyll impl the order of the crumbs is messed up. E.g. instead of

Home > Docs > Getting Started > Getting Started

I get

Home > Getting Started > /Docs >

Any idea where to start looking to figure out where the problem is?

**Comment by mosabua** [comment]
I have a feeling it is a consequence of wrong start values. I have page.url eval differently with URL 
http://localhost:4000/docs/getting-started/

With Java /docs/getting-started/index.md
With Ruby /docs/getting-started/index.html

**Comment by mosabua** [comment]
Another combo is

http://localhost:4000/docs/getting-started/initial-configuration.html
from docs/getting-started/initial-configuration.md

Ruby: Home > Docs > Getting Started > Initial Configuration
Java: Home > Getting Started > /Docs >

**Comment by bkiers** [comment]
Thanks Manfred, I'll have a look.

**Comment by bkiers** [comment]
This has to do with the fact that there is a nested `for` tag. The inner `for` messes up the variables of the outer `for`. Nasty one, let me think a bit on how to tackle this...

**Comment by bkiers** [comment]
@mosabua could you try the fix in https://github.com/bkiers/Liqp/pull/47 ?

**Comment by mosabua** [comment]
I can try it next week when I am back at work..

**Comment by bkiers** [comment]
Great! 👍

**Comment by mosabua** [comment]
I tested this now with the 0.6.8-SNAPSHOT from the PR branch and that works!

**Comment by mosabua** [comment]
So from my perspective you can merge and release. Let me know if you need help with the release to the Central Repository..

**Comment by bkiers** [comment]
> I tested this now with the 0.6.8-SNAPSHOT from the PR branch and that works!

Cool, I'll tidy up that branch and add some more unit tests for nested contexts soon. I've been a bit busy lately.

> So from my perspective you can merge and release. Let me know if you need help with the release to the Central Repository..

[Jason](https://github.com/jvanzyl) has been doing releases to Maven Central. If you're okay with it, I can ask him to provide you access as well. Then I'll give you push access to this repo and you can do releases too. Just let me know.

**Comment by mosabua** [comment]
I work with Jason so I will chat with him when I get a hold of him.

**Comment by bkiers** [comment]
Cool 👍

**Comment by bkiers** [comment]
Ok, the fix is in `master` and I've bumped the version. Feel free to release `master` to the Central Repository. 

I also added you as a collaborator in case you want to change versions before future releases and/or merge develop into master before releases.

Thanks!

**Comment by mosabua** [comment]
Great. I will just have to sort out the Central access.

**Comment by mosabua** [comment]
Release done.
