### ISSUE TITLE
Feature Question

### ISSUE THREAD

**Issue by smartytime** [bkiers/Liqp#51]
First of all, love the library.  

In our use case, we have a two-pass rendering.  The first pass has a certain set of models, and the second pass has a different set.  All the other filters are the same, but I could foresee a setup that used different filters based on the rendering mode.

What would be awesome is if we could tell the renderer/parser which items should be purposely ignored.  If the parser encountered these items, it would leave those liquid expression in place.

Is this possible today?  And could this be done without introducing a lot of complexity?

**Comment by bkiers** [comment]
Hi @smartytime, could you give a concrete example of this?
