### ISSUE TITLE
Allow escaping quotes in assign tags

### ISSUE THREAD

**Issue by oetting** [bkiers/Liqp#52]
Parsing a template with an escaped quote in an assign tag fails. So the following template does not work. 

    {% assign test = "f\"oo" %} Test: {{test}}

I have tested with the following java code:

    Template.parse("{% assign test = \"f\\\"oo\" %} Test: {{test}}");

I would expect it to be possible to escape quotes in the assign tag. Please let me know if I have misunderstood something or you need more information.

**Comment by bkiers** [comment]
AFAIK, escape sequences inside strings are not allowed. If you want to output a double quotes string, use single quotes:

    {% assign test = 'f"oo' %}

and for a single quote, use a double quoted string literal:

    {% assign test = "f'oo" %}

In case you need both quotes, use `&quot;` (or `&apos;`):

    {% assign test = "f'o &quot; o" %}

**Comment by oetting** [comment]
You are right. I have tested with the shopify liquid implementation, and it is not supported. Sorry about the noise.

FWIW capture tags is another way of handling content with both quote types.

**Comment by bkiers** [comment]
👍 no problem @oetting
