### ISSUE TITLE
Template.render() leaving Executor threads active

### ISSUE THREAD

**Issue by mehtasankets** [bkiers/Liqp#53]
Template.render() method is creating a separate thread which is not getting closed explicitly. Method should ideally call executorService.shutdown() explicitly to properly close the thread.

Not closing threads explicitly is causing multiple threads to be alive in the system and causes problems at the time of closing the process.

**Comment by bkiers** [comment]
Thanks @mehtasankets!

**Comment by mehtasankets** [comment]
Welcom @bkiers .. Can we have new version published with this change? 
Also, per my understanding this is a temporary fix and ideally the method should accept ExecutorService so that thread pool and thread management can be pushed back to the client using the library instead of library creating new threads on its own. Any thoughts?

**Comment by bkiers** [comment]
Ah, yeah, that would be nice. How about something like this: https://github.com/bkiers/Liqp/commit/bf4a522bdf1e2d6756aca85b0d83063e7dccaa57 (on a separate branch for now)

**Comment by mehtasankets** [comment]
@bkiers yes, above fix looks good to me.. 
Would you be able to publish a new jar with that change?

**Comment by bkiers** [comment]
The current release, 0.7.2, already has the shutdown of the exe-service:

```java
    public String render(final Map<String, Object> variables) {

        if (this.templateSize > this.protectionSettings.maxTemplateSizeBytes) {
            throw new RuntimeException("template exceeds " + this.protectionSettings.maxTemplateSizeBytes + " bytes");
        }

        final LiquidWalker walker = new LiquidWalker(new CommonTreeNodeStream(root), this.tags, this.filters, this.parseSettings.flavor);

        ExecutorService executorService = Executors.newSingleThreadExecutor();

        Callable<String> task = new Callable<String>() {
            public String call() throws Exception {
                try {
                    LNode node = walker.walk();
                    Object rendered = node.render(new TemplateContext(protectionSettings, renderSettings, parseSettings.flavor, variables));
                    return rendered == null ? "" : String.valueOf(rendered);
                }
                catch (Exception e) {
                    throw new RuntimeException(e);
                }
            }
        };

        Future<String> future = executorService.submit(task);
        try {
            return future.get(this.protectionSettings.maxRenderTimeMillis, TimeUnit.MILLISECONDS);
        }
        catch (TimeoutException e) {
            throw new RuntimeException("exceeded the max amount of time (" +
                    this.protectionSettings.maxRenderTimeMillis + " ms.)");
        }
        catch (Throwable t) {
            throw new RuntimeException("Oops, something unexpected happened: ", t);
        }
        finally {
            executorService.shutdown();
        }
    }
```

Or do you want a new release of master?

**Comment by mehtasankets** [comment]
I would actually need a new version with 
`Future<String> future = executorService.submit(task);` 
inside try-catch. My application actually broke at that line.

Would you kindly provide a new jar?

**Comment by bkiers** [comment]
If you only need the JAR, you can assemble it yourself by doing a `mvn clean install` in the root of the project (it will be located here: `./target/liqp-0.7.3-SNAPSHOT.jar`).

If you want a new version in in Maven Central, I'll need to ask someone else.

**Comment by mehtasankets** [comment]
I would need it via maven central as I have different environments where I run my program and otherwise I'll have to install it everywhere.

**Comment by bkiers** [comment]
OK, I've asked for a new release to Maven Central: https://github.com/bkiers/Liqp/issues/72

**Comment by mosabua** [comment]
http://repo1.maven.org/maven2/nl/big-o/liqp/0.7.3/
