### ISSUE TITLE
Test \r\n in WhitespaceControlTest.java

### ISSUE THREAD

**Issue by ilg-ul** [bkiers/Liqp#68]
Although with the current version that always removes **all** whitespaces it might not be a problem, for correctness, I think it would be better to also test Windows specific cases too.

This means doubling all tests that use `\n` with similar ones using `\r\n`.

In my fork that removes only one line terminator, the test file looks like this:

- https://github.com/gnu-mcu-eclipse/Liqp/blob/ilg-whitespaces/src/test/java/liqp/tags/WhitespaceControlTest.java

The adjusted parser that passes these tests is:

- https://github.com/gnu-mcu-eclipse/Liqp/blob/ilg-whitespaces/src/main/antlr3/liqp/parser/Liquid.g

**Comment by bkiers** [comment]
With the rewrite of the grammar (from v3 to v4), the Windows `\r\n` pass out of the box. Unit tests are added in https://github.com/bkiers/Liqp/pull/81
