### ISSUE TITLE
Help understand the security against reflection methods

### ISSUE THREAD

**Issue by ucjonathan** [bkiers/Liqp#69]
Can you help me understand the code base and how it prevents the untrusted user writing the template from calling methods like class loader methods, reflection, etc.

**Comment by mosabua** [comment]
As far as I know it does not prevent that. Whatever tool embeds liqp would have to do that imho as it should not be the concern of liqp itself to worry about that. In any case.. why do you want to know? The code is open source so you can see how it all works..
