### ISSUE TITLE
Release 0.7.3

### ISSUE THREAD

**Issue by bkiers** [bkiers/Liqp#72]
Hi @mosabua, could you create a new release to Maven Central from `master`?

**Comment by mosabua** [comment]
On it.

**Comment by mosabua** [comment]
Released on OSSRH 
https://oss.sonatype.org/content/repositories/releases/nl/big-o/liqp/0.7.3/

**Comment by mosabua** [comment]
Should be synced to Central  Repository shortly. 

http://repo1.maven.org/maven2/nl/big-o/liqp/

**Comment by bkiers** [comment]
Great, thanks!

**Comment by mosabua** [comment]
💥   http://repo1.maven.org/maven2/nl/big-o/liqp/0.7.3/

**Comment by mehtasankets** [comment]
Thanks guys. Appreciate your quick help on this.. :+1:
