### ISSUE TITLE
Setting locale

### ISSUE THREAD

**Issue by uhinze** [bkiers/Liqp#73]
I'd like to somehow specify the locale which is used by the date filter.

In `Date` there is a function `setLocale()`, which is not in use. Also, as `Date` isn't public, I can't call the function myself.

**Comment by bkiers** [comment]
Ah, `Date` should have been `public`. Fixed in https://github.com/bkiers/Liqp/pull/74

**Comment by uhinze** [comment]
Thanks @bkiers !
