### ISSUE TITLE
Parse Exception

### ISSUE THREAD

**Issue by micahasmith** [bkiers/Liqp#78]
` {{ 'general.meta.tags' | t: tags: meta_tags }}`

Seeing exceptions on any tags with that `t: tags: meta_tags` sorta structure.

Any ideas?

**Comment by bkiers** [comment]
Is that valid syntax? When separating filters, shouldn't they be separated with a `|`, and since the `t` doesn't have any parameters, should't it be without the `:`?

```
{{ 'general.meta.tags' | t | tags: meta_tags }}
```

See: https://help.shopify.com/themes/liquid/filters

If that syntax is valid, could you please post a link where this is explained?

Thanks!

**Comment by micahasmith** [comment]
Thanks for responding.

Yeah, its pretty weird. See the "Interpolation of template key arguments" section.

https://help.shopify.com/themes/development/internationalizing/translation-filter

**Comment by bkiers** [comment]
Thanks for the link. I see this `t` is a built-in filter used for locales, which is [not implemented in Liqp](https://github.com/bkiers/Liqp/tree/master/src/main/java/liqp/filters). 

I'll have a closer look to see if I can support this.

**Comment by micahasmith** [comment]
thank you for all of your help.

one thing that may allow someone like me (as in, not badass at parser/grammars) to solve problems like this for myself, is the option to have a "catch-all" or "fall-back"

for example, instead of throwing the `no filter available named:` exception, if i could have a catch-all filter or a fall back or a function that gets called with data like:

 - what the text was inside this filter
 - current state of processing the tag

then i could program in custom stuff that may be parser/generator unfriendly. or unfriendly to your goals with this project

just an idea.

**Comment by bkiers** [comment]
It's a good idea, and it's already in place. For example, writing a custom `t` filter is possible like this:

```java
Filter.registerFilter(new Filter("t"){
  @Override
  public Object apply(Object value, TemplateContext context, Object... params) {
    return String.format("TODO: handle value='%s', param=%s", value, params[0]);
  }
});

String rendered = Template.parse("{{ 'general.meta.tags' | t: 42 }}").render();

System.out.println(rendered);
```

which displays: `TODO: handle value='general.meta.tags', param=42`

The only thing that is not supported yet is the way the parser handles `filter: key: value` input.

**Comment by bkiers** [comment]
Okay,fixed in https://github.com/bkiers/Liqp/pull/80/commits/8028cea9475f6042d05cd24acdcf7fe299be5458

After it's merged, you can do something like this:

```java
Filter.registerFilter(new Filter("t"){
    @Override
    public Object apply(Object value, TemplateContext context, Object... params) {

        String outputValue = super.asString(value);
        Map<String, Object> param1 = super.asMap(params[0]);
        Map<String, Object> param2 = super.asMap(params[1]);

        return String.format("outputValue -> %s\nparam1      -> %s\nparam2      -> %s",
                outputValue, param1, param2);
    }
});

String data = "{ \"comment\": { \"author\": \"Someone\", \"email\": \"test@example.com\" } }";
String source = "{{ 'layout.comment.metadata' | t: author: comment.author, email: comment.email  }}";
String rendered = Template.parse(source).render(data);

System.out.println(rendered);
```

displays:

```
outputValue -> layout.comment.metadata
param1      -> {author=Someone}
param2      -> {email=test@example.com}
```

Note that since `t` is not a standard Liquid tag, it won't be part of Liqp.

**Comment by micahasmith** [comment]
!!! wow, this is awesome!
