### ISSUE TITLE
Suggestion: Reserve Java module name

### ISSUE THREAD

**Issue by mbaumbach** [bkiers/Liqp#89]
I'm not sure what the effort is to adopt this library to the Java module system, but in doing this with my own work, I've found it's good to [follow this advice](http://branchandbound.net/blog/java/2017/12/automatic-module-name/) and reserve a module name before even moving a library to be modular. This is as simple as modifying the main pom.xml:

```
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>3.0.2</version>
        <configuration>
          <archive>
            <manifest>
              <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
            </manifest>
            <manifestEntries>
              <Automatic-Module-Name>liqp</Automatic-Module-Name>
            </manifestEntries>
          </archive>
        </configuration>
      </plugin>
```

This allows consumers using Java 9+ modules to depend on this library before it even adopts modules without concern that the module name will change.

I originally thought `nl.big-o.liqp` would be good a module name, but the hyphen is an invalid character in module names. Also, using just `liqp` would mean that if anybody is already using this library in Java 9 as an automatic module, they wouldn't break should you decide to add this change.

I'm also glad to help modularize the library if you need any assistance. This library has been great for me, so always happy to contribute back. 👍

**Comment by bkiers** [comment]
Hi Marc! Thanks, modules sound like a good addition to this lib. 

I haven't done any real Java development in the past couple of years, so I'm not mr. current affairs w.r.t. Java 8 or later. So excuse the (perhaps) naive questions:

- when supporting modules, will the source- and/or target of the `maven-compiler-plugin` also be upped to Java 9?
- will the group-id and/or artifact-id in the POM need to change, or can they remain the same?

> ...  so always happy to contribute back.

That would be highly appreciated!

**Comment by mbaumbach** [comment]
Not naive questions at all, I'm a very active Java developer and all of this module stuff is just starting to become something I pay attention to. :)

To answer those questions:

- The source and target do not need to be modified yet. The presence of the `Automatic-Module-Name` in the `MANIFEST.MF` will mean that people who consume the library and are running in a Java 9+ modular environment, will be able to depend on this library using a module name you're defining now. You don't even need to modularize this library, but should you decide to in the future, it helps reduce the chance that consumers of it will have to change anything. If you plan to upgrade this to support modules, you will want to modify the `maven-compiler-plugin` to use the new `release` setting, which is a replacement for the source and target.
- The group and artifact IDs in the POM do not need to change.

I think it's still pretty early to adopt Java 9 as a required JVM for a library like this, especially because Java has made it pretty easy for people running Java 9+ to continue running non-modular projects without much effort. There are ways to make the library be fully modularized and still support older JVMs, but it can be a bit of a build juggling problem that's probably not worth the effort. Some more info on how that's done is here: https://maven.apache.org/plugins/maven-compiler-plugin/examples/module-info.html

A general summary of Java 9 modules in a world where Maven is basically a requirement:

> Maven is about pulling in the correct versions of dependent libraries. Java modules are about enforcing compile and runtime encapsulation of packages. Java modules expose or hide packages to create a more fine-grained API that cannot be accomplished with the built-in access modifiers (e.g., private, public, protected)

My personal recommendation is to reserve the module name with the modifications to the main pom.xml and adopt the Java module system once it's more predominant. If that's cool with you, I'll be happy to submit a pull request for it.

Thanks!

**Comment by bkiers** [comment]
Thanks for the elaborate explanation!

> [...] If that's cool with you, I'll be happy to submit a pull request for it.

That'd be great!

**Comment by mbaumbach** [comment]
Thanks for merging the change in! Do you have any plans to push out a new release to Maven Central with the changes since you've adopted ANTLR4?

**Comment by bkiers** [comment]
Yes, I've asked Manfred for a new release to Maven Central: https://github.com/bkiers/Liqp/issues/91

**Comment by mosabua** [comment]
Release done .. so this can probably be closed..
