### ISSUE TITLE
Comment blocks fail to parse if start or end tag is found inside

### ISSUE THREAD

**Issue by mbaumbach** [bkiers/Liqp#94]
Based on the [definition of a Comment tag](https://shopify.github.io/liquid/tags/comment/), it appears that anything between a `{% comment %}` and `{% endcomment %}` should simply be omitted from the output:

> Allows you to leave un-rendered code inside a Liquid template. Any text within the opening and closing comment blocks will not be output, and **any Liquid code within will not be executed**.

However, the following code fails to parse:

```
{% comment %}
    {% if true %}
        hello
    {% endif %}
{% endcomment %}
```

The exception generated:

```
at liquid.parser.v4.LiquidParser.comment_tag(LiquidParser.java:847)
        at liquid.parser.v4.LiquidParser.tag(LiquidParser.java:443)
        at liquid.parser.v4.LiquidParser.atom(LiquidParser.java:332)
        at liquid.parser.v4.LiquidParser.block(LiquidParser.java:211)
        at liquid.parser.v4.LiquidParser.parse(LiquidParser.java:154)
        at liqp.Template.parse(Template.java:138)
        at liqp.Template.<init>(Template.java:77)
```

I think the problem is the `comment_body` definition in `LiquidParser.g4`:

```
comment_tag
 : tagStart CommentStart TagEnd comment_body tagStart CommentEnd TagEnd
 ;

comment_body
 : other_than_tag_start
 ;

other_than_tag_start
 : ~( TagStart | TagStart2 )*
 ;
```

I would think this might be the correct definition:

```
comment_tag
 : tagStart CommentStart TagEnd other? tagStart CommentEnd TagEnd
 ;
```

I don't know enough about ANTLR to be confident in that answer though. 😂

**Comment by bkiers** [comment]
> ...
> I don't know enough about ANTLR to be confident in that answer though. 😂

Close, but since `other` only matches one or more `Other` tokens (which does not inluce `TagStart` and `OutStart` tokens), I defined it like this instead:

```
comment_tag
 : tagStart CommentStart TagEnd .*? tagStart CommentEnd TagEnd
 ;
```

where `.*?` un-greedily matches zero or more tokens until `tagStart CommentEnd TagEnd` is matched.

Thanks for the report!
