### ISSUE TITLE
Includes with path characters appear invalid

### ISSUE THREAD

**Issue by jvanzyl** [bkiers/Liqp#95]
Exception in thread "main" java.lang.RuntimeException: could not parse input: {% include wmt/html-head.html %}

<div class="wrap">
  {% include wmt/header.html %}
  <div class="margin-bottom-20"></div>
  <div class="container">
    {{content}}
  </div>
</div>

{% include wmt/footer.html %}

I took a cursory look at the grammar and appears that allowing the '/' in there would fix this?

**Comment by bkiers** [comment]
Indeed, added `/` and `\` to the lexer. Thanks!
